name: Deploy to Railway

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: ddbef286-2805-49ec-9c83-bdc4708d88d9
          projectId: 1074c967-78fa-46bf-a80f-00cdb33e05fa
          serviceId: production